### ISSUE TITLE
Top Browser Domains and URLs are not showing

### ISSUE THREAD

**Issue by BelKed** [ActivityWatch/aw-webui#357]
After upgrading to the latest beta (`v0.12.0b3`), "Top Browser Domains" and "Top Browser URLs" are not showing:

![Screen Shot](https://user-images.githubusercontent.com/66956532/183727415-10fb8b66-a97e-4683-8b9f-b6bc330bb1eb.png)

But the watcher is running, and data are in the requested bucket (`aw-watcher-web-firefox`):

![Screen Shot](https://user-images.githubusercontent.com/66956532/183727427-94df1f95-c35e-4e3c-abec-0f3cf295aa7f.png)

**Comment by ErikBjare** [comment]
This is actually what I was referring to in the release notes for `v0.12.0b3`. 

It has been fixed, and will be in the next release.

**Comment by TschuttGR** [comment]
Running v0.12.2, browser: Librewolf, os: MacOS 12. 
The issue is still not fixed: I have exactly the same situation as @BelKed.

**Comment by SoutrikDas** [comment]
Currently on v0.13.1 
Browser : Brave 
OS : MacOS 15 
Same stuff basically , url is being loaded into the buckets but the Top Browser Domains and Top Browser URLs Visualisations are saying they have no data.
